# Generated by Django 3.2 on 2021-08-19 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_auto_20210511_1345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Standard',
            new_name='Course_level',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='Standard',
            new_name='Course_level',
        ),
        migrations.AlterField(
            model_name='slotsubject',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_level_slots', to='curriculum.standard'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_level', to='curriculum.standard'),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_level_time_slots', to='curriculum.standard'),
        ),
        migrations.AlterField(
            model_name='workingdays',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_level_days', to='curriculum.standard'),
        ),
    ]
